version: '3'

services:
  flask-app:
    image: flask-app:latest
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-flask
    volumes:
      - "./src/:/app/app/"
      - "./conf/gunicorn.conf.py:/app/conf/gunicorn.conf.py"
      - "./data/:/app/data/" # save coordinates data
    expose: 
        - "5000"
    networks:
      - web-net

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./src/html/:/usr/share/nginx/html/"
    depends_on:
        - flask-app
    networks:
      - web-net

networks:
  web-net: