version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - "9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "connect-test:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-connect-standalone:
    image: wurstmeister/kafka
    container_name: connect-standalone
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - kafka
    volumes:
      - .:/home
    command: ["/home/start-kafka-connect.sh"]