version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.7
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "connect-test:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
        - "37017:27017"
    volumes:
        - "./mongo:/docker-entrypoint-initdb.d"
        - "data_db:/data/db"

  connect-kafka-mongo:
    image: mongo-kafka-connector:1.0.1
    build:
      context: "./connector/"
      dockerfile: Dockerfile
    container_name: connect-kafka-mongo
    depends_on:
      - kafka
      - mongo
    volumes:
      - "./connector/config/:/home/config/"
      - "./data/:/home/data/"


# incompatible file system between windows and mongo,
# so have to use volume:
# docker volume [prefix]_data_db will be created automatically
volumes: 
    data_db: