version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    ports:
      - "1111:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.2:1111
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topics_flume_kafka:2:2"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    ports:
      - "2222:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.2:2222
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flume:
    image: flume:1.9.0
    container_name: flume
    ports:
      - "44444:44444"
    depends_on:
      - kafka-1
      - kafka-2
    volumes:
      - ./flume:/opt/flume/conf/usr